/**
 * @description      : Constant class
 * @author           : Saddam Hussain
 * @last modified on : 19-12-2022
 * @last modified by : Saddam Hussain
 * Ver    Date    		Author  		Modification
 * 1.0  16-12-2022     Saddam Hussain  Initial Version 
**/
public class Constant {

    public static String prospectingStage = 'Prospecting';
    public static String closedWonStage = 'Closed Won';
    public static Date today = system.today();
    public static String companyName = 'Company Name';
    public static String phone = 'Phone';
    public static String email = 'Email';
    public static String firstName = 'Personal First Name';
    public static String lastName = 'Personal Last Name';
    public static String productUUID = 'Product UUID';
    public static String productQuantity = 'Product Quantity';
    public static String productList = 'ProductList';
    
    
}